"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CrispProvider from "./components/CrispProvider";
import dynamic from "next/dynamic";

const AnimatedCursor = dynamic(() =>
  import("react-animated-cursor").then((mod) => mod.default),
);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="mytheme" lang="en">
      <CrispProvider />
      <body className={inter.className}>
        <AnimatedCursor
          innerSize={0}
          outerSize={16}
          color="255, 255, 255"
          innerScale={0}
          outerAlpha={1}
          outerScale={2}
          outerStyle={{
            mixBlendMode: "exclusion",
          }}
          clickables={[
            "a",
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            "label[for]",
            "select",
            "textarea",
            "button",
            ".link",
            "video",
            {
              target: ".cursor-button-card",
              ...{
                outerScale: 8,
                innerSize: 16,
                innerScale: 6,
                innerStyle: {
                  backgroundImage: 'url("/view-project.svg")',
                  backgroundSize: "contain",
                  backgroundRepeat: "no-repeat",
                  backgroundPosition: "center",
                },
              },
            },
            {
              target: ".cursor-text-xxl",
              ...{
                outerScale: 12,
              },
            },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
